export const PLANS = {
  test_7days: {
    id: 'test_7days',
    name: 'Tester Pack',
    price: 10,
    amountInPaise: 10 * 100,
    durationDays: 7,
    perMonth: null,
    badge: null,
    savingsText: null,
    description: 'Special ₹10 tester pack (valid for 7 days). Exclusive for live testing.',
  },
  monthly: {
    id: 'monthly',
    name: '1 Month Starter',
    price: 199,
    amountInPaise: 199 * 100,
    durationDays: 30,
    perMonth: 199,
    badge: 'STARTER',
    savingsText: null,
    description: 'Billed monthly. Unlimited catalog & fast counter billing.',
  },
  quarterly: {
    id: 'quarterly',
    name: '3 Months Value',
    price: 498,
    amountInPaise: 498 * 100,
    durationDays: 90,
    perMonth: 166,
    badge: 'MOST POPULAR',
    savingsText: 'Save 17%',
    description: 'Just ₹166/month. Billed ₹498 for 3 months. Most popular choice.',
  },
  semi_annual: {
    id: 'semi_annual',
    name: '6 Months Super Saver',
    price: 900,
    amountInPaise: 900 * 100,
    durationDays: 180,
    perMonth: 150,
    badge: 'BEST VALUE',
    savingsText: 'Save 25%',
    description: 'Just ₹150/month. Billed ₹900 for 6 months. Maximum savings.',
  },
  // Backward compatibility alias for legacy records
  yearly: {
    id: 'yearly',
    name: '6 Months Super Saver',
    price: 900,
    amountInPaise: 900 * 100,
    durationDays: 180,
    perMonth: 150,
    badge: 'BEST VALUE',
    savingsText: 'Save 25%',
    description: 'Just ₹150/month. Billed ₹900 for 6 months. Maximum savings.',
  },
} as const;

export type PlanType = keyof typeof PLANS;
